using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HealthSystem2._0
{  
    class PlayerCharacter
    {
        public int maxHealth;
        public int currentHealth;

        public int maxShield;
        public int currentShield;

        public int maxLives;
        public int currentLives;

        public int damage;

        public PlayerCharacter()
        {
            maxHealth = 100;
            currentHealth = 100;

            maxShield = 50;
            currentShield = 50;

            maxLives = 3;
            currentLives = 3;
        }
        public void TakeDamage(int damage)
        {

            Console.WriteLine("Took " + damage + " Damage!");
            if (currentShield >= 0)
            {
                currentShield = currentShield - damage;

                if (currentShield < 0)
                {
                    currentShield = 0;
                    currentHealth = currentHealth - damage;

                    if (currentHealth <= 0)
                    {
                        currentHealth = 0;
                        Console.WriteLine("You've died!");
                        currentLives--;
                        if (currentLives > 0)
                        {
                            currentHealth = maxHealth;
                            currentShield = maxShield;
                        }
                    }
                }
            }
        }

        public void RegenerateShield(int shieldGen)
        {
            if (currentShield < maxShield)
            {
                currentShield = currentShield + shieldGen;
                
                if (currentShield > maxShield)
                {
                    currentShield = maxShield;
                }
            }

            Console.WriteLine("Shield Regenerated by: " + shieldGen);
        }

        public void TEMPHUD()
        {

            Console.WriteLine("===============");
            Console.WriteLine("Health: " + currentHealth + "/" + maxHealth);
            Console.WriteLine("Shield: " + currentShield + "/" + maxShield);
            Console.WriteLine("Lives: " + currentLives + "/" + maxLives);
            Console.WriteLine("===============");
        }
    }
}
